### ISSUE TITLE
RimPy compatibility Issue

### ISSUE THREAD

**Issue by kotlerbunny** [DianaWinters/Orassans#25]
[RimPy modmanager](https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158) does not properly process all folders when stripping the mod, due to errors in the Orassan's [LoadFolders.xml](https://github.com/DianaWinters/Orassans/blob/master/LoadFolders.xml) file.
The file uses `<l1>` instead of `<li>` tags. (`<l1>1.3</l1>`, for example).

This xml variation leads to the fact that if RimPy's "mod stripping" function is not used carefully enough, it deletes folders `1.0`, `1.1`, `1.2` and `1.3`, instead of leaving the folder corresponding to the current Rimworld version. And this is breaks the mod.

**Comment by DianaWinters** [comment]
Could you explain what changes you want me to make?
